services:
  backend:
    image: openjdk:20
    volumes:
      - ./build/libs/LibrarianAPI-1.0.0.jar:/app/librarian-api-1.0.0.jar
    command: java -jar /app/librarian-api-1.0.0.jar
    ports:
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: jdoconnell/h2:latest
    ports:
      - 9092:9092
    volumes:
      - h2-data:/path/to/h2/data

volumes:
  h2-data:
    driver: local
